### ISSUE TITLE
ignoreCommitsOlderThan don't work

### ISSUE THREAD

**Issue by polter05** [tomasbjerre/git-changelog-command-line#10]
The parameter -ignore-older-than don't work properly due to DEFAULT_DATEFORMAT which is egal to YYYY-MM-dd HH:mm:ss.

This is must be replace by yyyy-MM-dd HH:mm:ss (minor yyyy) in the API project `src/main/java/se/bjurr/gitchangelog/api/GitChangelogApiConstants.java`

**Comment by tomasbjerre** [comment]
Thanks for reporting and PR. Released the fix now.

https://github.com/tomasbjerre/git-changelog-lib/pull/122
