### ISSUE TITLE
Example template licensing question

### ISSUE THREAD

**Issue by mschilli87** [tomasbjerre/git-changelog-command-line#12]
Dear @tomasbjerre,

First of all, thank you for this fantastic tool.
I am using it to generate the changelog for a package released under the AGPL3+.
However, I want to include the scripts and templates for build and release chores which includes my Mustache template for the `CHANGELOG.md` file and I'd like to distribute that template under the [GNU All-Permissive License](https://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html). Since that file is basically just a modified version of [your Conventional Commits example](https://github.com/tomasbjerre/git-changelog-command-line#example---semantic-versioning-from-conventional-commits), I wanted to double-check with you: Are you fine with me releasing 'my' work derived from your example under that license? Do you want me to still reference/include the Apache 2.0 License in my package? Do you want me to list you as a copyright holder of that file (and thus my package) or do you consider that snippet copyright-free so I can treat it as if I started my template from scratch instead of tweaking your example to suit my needs?
I guess the whole idea is for people to re-use that code but better safe than sorry. :wink: 

Thank you in advance for any clarification.

Best,
Marcel

**Comment by tomasbjerre** [comment]
I am totally ok with you treating it as copyright free!

**Comment by mschilli87** [comment]
Thank you for your fast reply. Happy hacking!
