### ISSUE TITLE
Update Jackson Dependencies to Resolve Security Vulnerabilities

### ISSUE THREAD

**Issue by ksh-t-z** [tomasbjerre/git-changelog-command-line#19]
**Description:**
The `git-changelog-command-line` project is currently using outdated versions of Jackson libraries:
- `com.fasterxml.jackson.core:jackson-core:2.5.3`
- `com.fasterxml.jackson.core:jackson-databind:2.5.3`
- `com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.5.3`

These versions have multiple Critical and High CVEs associated with them, which are flagged during security scans of the Docker image.

**Proposed Solution:**
Update the Jackson dependencies to the latest version 2.17.1:
- `com.fasterxml.jackson.core:jackson-core:2.17.1`
- `com.fasterxml.jackson.core:jackson-databind:2.17.1`
- `com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.1`

The latest versions can be found [here](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind).

**Benefits:**
- Resolves multiple security vulnerabilities.
- Ensures the Docker image is vulnerability-free.

**References:**
- [Jackson Databind 2.17.1](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.17.1)

Thank you for considering this update to improve the security of the project.

**Comment by tomasbjerre** [comment]
Stepping dependencies and releasing now.

**Comment by ksh-t-z** [comment]
Thanks @tomasbjerre 

Could you please also release the image tag on Docker Hub?

**Comment by tomasbjerre** [comment]
Image released now.

**Comment by ksh-t-z** [comment]
Thanks again
