### ISSUE TITLE
JIRA connection not initiated

### ISSUE THREAD

**Issue by usman-marshall** [tomasbjerre/git-changelog-command-line#20]
I am trying to replicate Jenkins plugin git-changelog-lib by using git-changelog-command-line. The command works fine to find issues from git but doesn't fetch JIRA title as I have verified that with tcpdump (simple curl to JIRA produces tcpdump but executing this lib command doesn't). I am wondering what I am missing here, thanks for help. I use following command

```
npx git-changelog-command-line -ini --jira-enabled --jira-server "some.jira-server.com" --jira-username "someuser@blah.com" --jira-basic-auth $token --jira-pattern "\b(?i)ABC-([0-9]+)\b" -fre $latest_tag -std -tec "What's new:
{{#issues}}
  {{#hasIssue}}
- {{issue}} - {{title}}
  {{/hasIssue}}
  {{^hasIssue}}                                                 
- {{name}}
  {{/hasIssue}}
{{/issues}}"

```
Output is following without title
What's new:
- ABC-616 -

**Comment by tomasbjerre** [comment]
How do you use the Jenkins plugin?

**Comment by usman-marshall** [comment]
I am using Git Changelog Plugin and configured as this

![1](https://github.com/user-attachments/assets/da345936-ce99-4eff-a899-1d5064dc9bef)
![2](https://github.com/user-attachments/assets/fba68790-2898-4ee1-88d9-45f157a91fbf)
![3](https://github.com/user-attachments/assets/0885ee89-3aa7-4067-a4fc-cd9e3f28605a)
![4](https://github.com/user-attachments/assets/927102f0-a806-4bfb-aeb5-6dd59a17c1f9)

**Comment by tomasbjerre** [comment]
I think you are using wrong credentials.

**Comment by usman-marshall** [comment]
Credentials in JIRA is configured like this and works fine in plugin
![5](https://github.com/user-attachments/assets/0ce99afb-8cf2-4661-8d87-b5edfc1b2adc)

How do you think it should be in command line?

**Comment by tomasbjerre** [comment]
Looks like Jenkins is using username/password and here you have this instead of password:
`--jira-basic-auth $token`

**Comment by usman-marshall** [comment]
I have now tried to use the token both as password and bearer-token too but not worked. Shouldn't the lib initiate request to JIRA even if it used with wrong authentication type?
I will confirm what type of token it is with my colleague tomorrow.

**Comment by usman-marshall** [comment]
Given everything else same, just adding ---use-integrations flag made it work. I thought adding --jira-enabled would be enough. May be a clarification in the help text would help others.
