### ISSUE TITLE
kickstart to run it

### ISSUE THREAD

**Issue by hannesa2** [tomasbjerre/git-changelog-command-line#3]
Following the README.md
<img width="749" alt="image" src="https://user-images.githubusercontent.com/3314607/39033533-ce232de0-4472-11e8-8862-40368a5b1505.png">

I found no zip (only ArtifactId=git-release-notes has a zip)

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/3314607/39033520-becb8fd6-4472-11e8-8d51-04f8b485b746.png">

Ok, I build for my own with

`./gradlew build --stacktrace -i`

`./build/scripts/git-changelog-command-line -t changelog.mustache -sf changelog.json -of CHANGELOG.md`

but it delivers

> Error: Could not find or load main class se.bjurr.gitchangelog.main.Main

So I result in two questions:
A: where do I found a running artifact ?
B: (more important) how to build it by my own and run it ?

**Comment by tomasbjerre** [comment]
I uploaded a snapshot here:
https://github.com/tomasbjerre/git-changelog-command-line/releases/tag/180420

I'll work on getting it on central again when I have time.
