### ISSUE TITLE
Cannot download bin files

### ISSUE THREAD

**Issue by vavdav** [tomasbjerre/git-changelog-command-line#4]
Hello, please where can I download that zip? I am not java developer and I have issues to run it.

https://search.maven.org/search?q=a:git-changelog-command-line

here is not any zip file with bin

**Comment by tomasbjerre** [comment]
https://search.maven.org/remotecontent?filepath=se/bjurr/gitchangelog/git-changelog-command-line/1.39/git-changelog-command-line-1.39.zip
